name: Json Response Save

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  response_sync:

    runs-on: docker-maven

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute Google API and save response
        run: |
          curl -o response.json https://www.google.com

      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add response.json
          git commit -m "Add Google API response"
          git push
